# コメント書いたのGsanじゃなくて石部なのでコメント内容間違ってる可能性あり
# 訓練用データ数
num_data: 50
# トレーニング用データ数
num_test: 25
# 画像の大きさ
input_sizex: 572
input_sizey: 572
# ピクセルが黒か白か
num_class: 2
# U-Netの深さ(論文の図の灰色の線の数)
depth: 4
# フィルターの種類の数
layers_default: 8
# バッチ数
Batch_num: 23
# 学習回数
learnig_times: 1000
# 学習時何割くらいドロップアウトさせるか
keep_prob: 0.1
# tensorboardで何枚画像を表示するか
num_image: 4
